name: Create VSIX

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'VSCE')"
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        npm install 
        npm install vsce 
        npm install webpack
      
    - name: Create vsix
      run: | 
        npm run webpack 
        vsce package

    - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

    - name: Upload VSIX
        uses: actions/upload-artifact@v2
        with:
          path: vdm-vscode-${{ steps.package-node-version.outputs.version }}.vsix
          name: vdm-vscode-${{ steps.get_version.outputs.VERSION }}.vsix
